apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-web
  template:
    metadata:
      labels:
        app: blog-web
        istio-injection: enabled
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "15090"
        prometheus.io/path: "/stats/prometheus"


    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command:
          - /bin/sh
          - -c
          - |
            git clone --depth=1 https://github.com/knitas0891/blog_caffe.git /src
        volumeMounts:
        - name: html
          mountPath: /src
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        emptyDir: {}

