apiVersion: v1
kind: Service
metadata:
  name: blog-web-service
  namespace: blog
spec:
  type: LoadBalancer
  selector:
    app: blog-web
  ports:
  - protocol: TCP
    port: 8888         # Puerto externo del LoadBalancer
    targetPort: 80     # Puerto interno del contenedor (nginx)

